# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTTP-OAI
version:      3.19
version_from: lib/HTTP/OAI.pm
installdirs:  site
requires:
    CGI:                           0
    HTTP::Request:                 0
    HTTP::Response:                0
    LWP::UserAgent:                0
    Test::More:                    0
    URI:                           0
    XML::LibXML:                   1.58
    XML::SAX::Base:                1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
