--- #YAML:1.0
name:                HTTP-OAI
version:             3.22
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    CGI:                           0
    Encode:                        2.12
    HTTP::Request:                 0
    HTTP::Response:                0
    LWP::UserAgent:                0
    Test::More:                    0
    URI:                           0
    XML::LibXML:                   1.6
    XML::LibXML::SAX:              0
    XML::SAX::Base:                1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
