--- #YAML:1.0
name:               HTTP-OAI
version:            3.28
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI:               0
    Encode:            2.12
    HTTP::Request:     0
    HTTP::Response:    0
    LWP::UserAgent:    0
    Test::More:        0
    URI:               0
    XML::LibXML:       1.6
    XML::LibXML::SAX:  0
    XML::SAX:          0
    XML::SAX::Base:    1.04
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
